"""Keep commonly used functions here."""

import bpy
import bmesh
from mathutils import Vector
from math import sin, cos, pi, atan2
from functools import partial

from typing import Dict, List, Tuple, Optional, Union, Any

"""Parameters. This should be the default size referrence for everything afterward."""
SEGMENTS = 16 # this is curved surface resolution. Increase when needed more smoothness.
# hilt/shaft stat - this is VERY important at least on radius, as it is directly related to minifigure grip.
BAR_DIAMETER = 3.18 # in mm; this is the LEGO spec. Scale down as needed.
BAR_RADIUS = BAR_DIAMETER / 2 
HILT_LENGTH_ONE_HAND = BAR_DIAMETER * 2.3 # one handed (arming)
HILT_LENGTH_TWO_HAND = BAR_DIAMETER * 4 # two handed-ish (hand-and-a-half, longsword)
HILT_LENGTH_MASSIVE = BAR_DIAMETER * 6.2  # massive (zwei)
# blade sizes 
BLADE_THICKNESS = BAR_DIAMETER * 2/3 
BLADE_WIDTH = BAR_DIAMETER * 1.5
BLADE_LENGTH_DEFAULT = BAR_DIAMETER * 9 # arming/longsword range.
BLADE_LENGTH_LONG = BAR_DIAMETER * 11 # arming/longsword range.
BLADE_LENGTH_MASSIVE = BAR_DIAMETER * 14 # zwei size
# crossguard sizes
CROSSGUARD_SMALL = BAR_DIAMETER             # chinese/japenese typed; a little bit bigger than BLADE_WIDTH to ensure fitting
CROSSGUARD_NORMAL = BAR_DIAMETER * 2        # normal sized (western swords)
CROSSGUARD_DEPTH = BAR_DIAMETER *2/3         # same dimension as blade length 
CROSSGUARD_THICKNESS = BAR_DIAMETER * 3 / 4 # same dimension as blade thickness, also a bit bigger

def create_meshes(generator_fn, name, additional_generator_fn=None, clean=False, **kwargs):
    """Generic function to create a mesh with a specific `name`. Mesh will be generated by `generator_fn`; any additional argument parsed here is transfered to that accordingly."""
    if clean:
        # Clean scene
        bpy.ops.object.select_all(action='SELECT')
        bpy.ops.object.delete(use_global=False)
    else:
        if name in bpy.data.objects:
            obj = bpy.data.objects[name]
            bpy.data.objects.remove(obj, do_unlink=True)
    
    # Create mesh and object
    mesh = bpy.data.meshes.new(name)
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    
    # Edit the mesh
    bm = bmesh.new()
    generator_fn(bm, **kwargs)
    if additional_generator_fn:
        for gen_fn in additional_generator_fn:
            gen_fn(bm)

    # Finish
    bm.to_mesh(mesh)
    bm.free()
    return obj



def create_surface(bm, top_vertices, bottom_vertices, form_complete_surface: bool=True, is_parallel: bool=False):
    """Create a generic shared surface between two set of vertices, triangle based.
    If form_complete_surface (default), this will also link up the first and last section together."""
    # this will assume the top vertices to be the wider one, so it's be priortized when assigning.
    if is_parallel:
        # specialized version, used when top/bottom are on parallelized planes, so simply use distance to assign 
        # this will not properly reaarrange bottom section
        core_lines = [(t, min(bottom_vertices, key=lambda b: (b.co-t.co).length)) for t in top_vertices]
        used_points = set((b for t, b in core_lines))
        additional_lines = [(min(top_vertices, key=lambda t: (t.co-b.co).length), b) for b in bottom_vertices if b not in used_points]
    else:
        # default (more generalized variant), assuming center is largely agnostic and top and bottom vector comparing to center are largely similar
        # first, calculate a generic center point
        center = sum([t.co for t in top_vertices], Vector((0, 0, 0))) / len(top_vertices) 
        # for each of the top vertices, find its most aligned vertices (same direction) instead 
        def calculate_similarity(b, t):
            bvector = (b.co - center).normalized()
            tvector = (t.co - center).normalized()
            return bvector.dot(tvector)
        core_lines = [(t, max(bottom_vertices, key=lambda b: calculate_similarity(b, t))) for t in top_vertices]
        used_points = set((b for t, b in core_lines))
        additional_lines = [(max(top_vertices, key=lambda t: calculate_similarity(b, t)), b) for b in bottom_vertices if b not in used_points]
        # reassign the bottom vertices by the direction which top_vertices move.
        start_vector = top_vertices[0]
        side_vector = top_vertices[len(top_vertices) // 3]
        plane_normalized_vector = (start_vector.co - center).cross(side_vector.co - center).normalized()
        true_start_vector = (start_vector.co - center).normalized()
        true_side_vector = (start_vector.co - center).cross(plane_normalized_vector).normalized()
        #print(true_start_vector, true_side_vector)
        def calculate_angle(b):
            bvector = (b.co - center)
            bangle = atan2(bvector.dot(true_start_vector), bvector.dot(true_side_vector))
            return bangle 
        # ensure sorted via Oxy direction first
        bottom_vertices = list(sorted(bottom_vertices, key=calculate_angle))
        # find the node closest to the start top vertex and rearrange
        best_match = max(bottom_vertices, key=lambda b: calculate_similarity(b, start_vector))
        best_match_index = bottom_vertices.index(best_match)
        #print(bottom_vertices, best_match_index)
        bottom_vertices = bottom_vertices[best_match_index:] + bottom_vertices[:best_match_index]

    all_lines = set(core_lines + additional_lines)
    # join the lines together using their original indexing for subsequent lining 
    lines = list(sorted(all_lines, key=lambda vp: (top_vertices.index(vp[0]), bottom_vertices.index(vp[1]) ) ))
    #print("AT:", [id(t) for t in top_vertices])
    #print("AB:", [id(b) for b in bottom_vertices])
    if form_complete_surface:
        previous_tv, previous_bv = lines[-1] # using the last line on the iteration for start, this should form fully sealed surfaces.
    else:
        previous_tv = previous_bv = None # do not put value; this will only deal with 1st item
    #print("T-B:", id(previous_tv), id(previous_bv))
    for tv, bv in lines: 
        if not previous_tv and not previous_bv:
            previous_tv, previous_bv = tv, bv 
            continue
        # perform binding
        #print("T-B:", id(tv), id(bv))
        if tv == previous_tv:
            # same top vert, only create the triangle surface 
            bm.faces.new([tv, previous_bv, bv])
        elif bv == previous_bv:
            # same bottom vert, only create the triangle surface 
            bm.faces.new([previous_tv, tv, bv])
        else:
            bm.faces.new([previous_bv, previous_tv, tv, bv])
            ## two different point, prioritizing tv faces IF NOT crossing. 
            #if(is_crossing(previous_bv.co, previous_tv.co, bv.co, tv.co)):
            #    # crossing happened, use bv-previous_tv diagonal instead
            #    bm.faces.new([previous_tv, previous_bv, bv])
            #    bm.faces.new([previous_tv, tv, bv])
            #else:
            #    # non-crossing happened, use tv-previous_bv
            #    bm.faces.new([previous_tv, tv, previous_bv])
            #    bm.faces.new([tv, previous_bv, bv])
        # set current coordinate as new  
        previous_tv, previous_bv = tv, bv 
    # shouldn't need to, but can try
    return bm

def form_side_surfaces(bm, all_points: List[list], exclude_faces: Optional[List[Tuple[int, int]]]=None):
    """For a 2D set of points NxP, form (N-1, P) faces along the points. This is used for forming tubes and surfaces etc.
    If supplied exclude_faces, the faces with position matched on that is not created and instead is returned; this should allow create_surface to interact with it"""
    # ensure it's proper 2d 
    lengths = [len(ps) for ps in all_points]
    assert all((l1 == l2 for l1, l2 in zip(lengths[:-1], lengths[1:]))), f"Invalid all_points supplied, all sections must match: {lengths}"
    # get any P from the list 
    length = lengths[0]
    if exclude_faces:
        excluded = dict()
    # building faces - i iterate P and j iterate N
    for i in range(length):
        for j in range(len(all_points)-1):
            v1 = all_points[j][i]
            v2 = all_points[j+1][i]
            v3 = all_points[j+1][(i+1)%length]
            v4 = all_points[j][(i+1)%length]
            if exclude_faces and (j, i) in exclude_faces:
                # this face is excluded; keep it in the dict 
                excluded[(j, i)] = [v1, v2, v3, v4]
            else:
                # this face is constructed like normal
                bm.faces.new([v1, v2, v3, v4])
    # if use the exclude_faces mechanism, return relevant dict
    if exclude_faces:
        return bm, excluded
    else:
        return bm

DEFAULT_PEG_HEIGHT = CROSSGUARD_DEPTH
DEFAULT_PEG_RADIUS = BAR_RADIUS * 0.66 
DEFAULT_SLOT_RADIUS = BAR_RADIUS + 0.1 # this is in mm; so this should be a little too conservative even.

def create_d_peg(bm, center=(0, 0, 0), radius=DEFAULT_PEG_RADIUS, height=-DEFAULT_PEG_HEIGHT, segments=SEGMENTS):
    """Creating a d-peg surface with closed "top" and open "bottom", so surface can join into each other.
    Will have segments / 2 (curve) + 3 (rectangular) nodes in the bottom. The bottom surface is aligned with center z
    Since this peg is protruding from above (blade) or intruding from below (hilt), height is negative
    """
    verts_top = []
    verts_bottom = []

    for i in range(segments):
        angle = 2 * pi * i / segments
        # Only keep right half (X ≥ 0)
        if sin(angle) >= -0.001:
            x = radius * sin(angle)
            y = radius * cos(angle)
            v_bot = bm.verts.new((x + center[0], y + center[1], center[2]))
            v_top = bm.verts.new((x + center[0], y + center[1], center[2] + height))
            verts_bottom.append(v_bot)
            verts_top.append(v_top)
            # print("added ", cos(angle), sin(angle))

    # Add flat back face on X = -radius
    v1_bottoms = [bm.verts.new((center[0] - radius, center[1] + y, center[2])) for y in [-radius, 0, radius]]
    v1_tops = [bm.verts.new((center[0] - radius, center[1] + y, center[2] + height)) for y in [-radius, 0, radius]]
    verts_bottom.extend(v1_bottoms)
    verts_top.extend(v1_tops)

    # Side walls
    size = len(verts_bottom)
    for i in range(size):
        v1 = verts_bottom[i]
        v2 = verts_bottom[(i + 1) % size]
        v3 = verts_top[(i + 1) % size]
        v4 = verts_top[i]
        bm.faces.new([v1, v2, v3, v4])

    # Cap top
    bm.faces.new(verts_top) 
    # try to give correctly oriented nodes 
    # peg_bottom = verts_bottom[-3:] + verts_bottom[:-3]
    # peg_bottom = verts_bottom[-1:] + verts_bottom[:-1]
    peg_bottom = verts_bottom
    return bm, peg_bottom 
